### PR TITLE
Publish token stream strategy in pubstrats

### LINKED ISSUE #55: Review Community Strat
Review community strategy in [PR 1](https://github.com/h20liquidity/h20.communitystrats/pull/1).

### PR DESCRIPTION
**Pull request by Siddharth2207**
## Motivation
Fixed grid strategy.

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [x] unit-tested any new functionality
- [x] linked any relevant issues or PRs

### CODE REVIEW

**Review by dcatki — COMMENTED** [review]
@Siddharth2207 a few of these have decimals and a few 1e18 etc - is that how it is supposed to be? e.g. 
          #Jittery binomial bits 
          jittery-binomial-bits: 10 
          
                          bindings:
                  twap-deviation: 3e16

**Comment by Siddharth2207** [comment]
> @Siddharth2207 a few of these have decimals and a few 1e18 etc - is that how it is supposed to be? e.g. #Jittery binomial bits jittery-binomial-bits: 10
> 
> ```
>                       bindings:
>               twap-deviation: 3e16
> ```

Yes correct, the `jittery-binomial-bits` is passed as a integer operand arg, so its `10` and not `10e18`.

**Review by thedavidmeister — CHANGES_REQUESTED** [review]
i need clarification on this, i've pinged in TG

**Comment by dcatki** [comment]
I've moved this back to priorities

Once the PAID strategies are tested this PR needs to be updated. actually it is to publish this code in pubstrats

**Pull request merged**
